arkaComp/urls.py
from django.contrib import admin  
from django.urls import path, include  
from arkademystore import views  


urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('inputProduk', views.inputProduk),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

arkademystore/models.py
from django.db import models  

# class Employee(models.Model):  
#     eid = models.CharField(max_length=20)  
#     ename = models.CharField(max_length=100)  
#     eemail = models.EmailField()  
#     econtact = models.CharField(max_length=15)  
#     class Meta:  
#         db_table = "loyee"  
    
class ArkademyStore(models.Model):  
    nama_produk = models.CharField(max_length=20)  
    keterangan = models.CharField(max_length=100)  
    harga = models.IntegerField() 
    jumlah = models.IntegerField()  
    class Meta:  
        db_table = "arkademystore"  

arkademystore/forms.py
from django import forms  
from arkademystore.models import ArkademyStore 
    
class ArkademyStoreForm(forms.ModelForm):  
    class Meta:  
        model = ArkademyStore
        fields = "__all__"  

arkademystore/views.py
from django.shortcuts import render, redirect  
from .forms import ArkademyStoreForm  
from .models import ArkademyStore  


    # Create your views here.  


def inputProduk(request):  
    if request.method == "POST":  
        form = ArkademyStoreForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = ArkademyStoreForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    arkademystores = ArkademyStore.objects.all()  
    return render(request,"show.html",{'arkademystores':arkademystores})  
def edit(request, id):  
    arkademystore = ArkademyStore.objects.get(id=id)  
    return render(request,'edit.html', {'arkademystore':arkademystore})  
def update(request, id):  
    arkademystore = ArkademyStore.objects.get(id=id)  
    form = ArkademyStoreForm(request.POST, instance = arkademystore)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'arkademystore': arkademystore})  
def destroy(request, id):  
    arkademystore = ArkademyStore.objects.get(id=id)  
    arkademystore.delete()  
    return redirect("/show")  

arkademystore/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>
  <div class="container-xl"></div>
    <form method="POST" class="post-form" action="/update/{{arkademystore.id}}">  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">nama_produk:</label>  
        <div class="col-sm-4">  
            <input type="text" name="nama_produk" id="id_nama_produk" required maxlength="20" value="{{ arkademystore.nama_produk }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">keterangan:</label>  
        <div class="col-sm-4">  
            <input type="text" name="keterangan" id="id_keterangan" required maxlength="100" value="{{ arkademystore.keterangan }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">harga :</label>  
        <div class="col-sm-4">  
            <input type="number" name="harga" id="id_harga" required maxlength="254" value="{{ arkademystore.harga }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">jumlah:</label>  
        <div class="col-sm-4">  
            <input type="number" name="jumlah" id="id_jumlah" required maxlength="15" value="{{ arkademystore.jumlah }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>  
        </div>  
    </form> 
  </div> 
</body>  
</html>  

arkademystore/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <title>Index</title>  
    {% load staticfiles %}  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
  <div class="container-xl">
    <h3>INPUT PRODUK</h3>  
    <form method="POST" class="post-form" action="/inputProduk">  
            {% csrf_token %}  
        <div class="container">  
        <br>  
        <div class="form-group row">  
          <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">   
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">nama_produk:</label>  
        <div class="col-sm-4">  
          {{ form.nama_produk }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">keterangan:</label>  
        <div class="col-sm-4">  
          {{ form.keterangan }}  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">harga:</label>  
        <div class="col-sm-4">  
          {{ form.harga }}  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">jumlah:</label>  
        <div class="col-sm-4">  
          {{ form.jumlah }}  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-primary">Submit</button>  
        </div>  
      </div>  
        </div>  
    </form>
 </div>
</body>  
</html>  

arkademystore/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Rekap produk</title>  
     {% load staticfiles %}  
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body class="showtable">
    <h1>DAFTAR PRODUK </h1>
    <div class="container-xl">
        <table class="table table-striped table-bordered table-sm">  
            <thead class="thead-dark">  
            <tr>  
                <th>nama_produk</th>  
                <th>keterangan</th>  
                <th>harga</th>  
                <th>jumlah</th>  
                <th>tindakan</th>  
            </tr>  
            </thead>  
            <tbody>  
        {% for arkademystore in arkademystores %}  
            <tr>  
                <td>{{ arkademystore.nama_produk }}</td>  
                <td>{{ arkademystore.keterangan }}</td>  
                <td>{{ arkademystore.harga }}</td>  
                <td>{{ arkademystore.jumlah }}</td>  
                <td>  
                    <a href="/edit/{{ arkademystore.id }}"><span class="linkedit" >Edit</span></a>  
                    <a href="/delete/{{ arkademystore.id }}"><span class="linkedit">Delete</a>  
                </td>  
            </tr>  
        {% endfor %}  
            </tbody>  
        </table>  
        <br>  
        <br>  
        <center><a href="/inputProduk" class="btn btn-primary"> tambah produk </a></center>  
    </div>
</body>  
</html>  